version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    env_file:
      - ./.env
    networks:
      - my-net
  nginx:
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - my-net
networks:
  my-net:
    driver: bridge
